### ISSUE TITLE
exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]

### ISSUE THREAD

**Issue by PatrickJnr** [Windows200000/TwitchDropsMiner-updated#107]
```
05:20:39: !!!required_minutes for "Wrest the Heart" is 0 This could be due to a subscription requirement, tracked in Issue #101!!!
05:20:41: Fatal error encountered:
05:20:41: 
05:20:41: Traceback (most recent call last):
05:20:41:   File "main.py", line 160, in main
05:20:41:   File "twitch.py", line 772, in run
05:20:41:   File "twitch.py", line 828, in _run
05:20:41:   File "inventory.py", line 237, in claim
05:20:41:   File "inventory.py", line 138, in claim
05:20:41:   File "inventory.py", line 154, in _claim
05:20:41:   File "twitch.py", line 1575, in gql_request
05:20:41: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
05:20:41: 
05:20:41: Exiting...
05:20:42: 
05:20:42: Application Terminated.
05:20:42: Close the window to exit the application.
```

**Comment by Windows200000** [comment]
#86
