### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\ud734' in position 31: illegal multibyte sequence

### ISSUE THREAD

**Issue by hurentian** [Windows200000/TwitchDropsMiner-updated#135]
While I was getting BlackDesert Drops, something went wrong.

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/38875515/0a7d2f3c-11e2-4a34-b0db-8619364758b6)

```
22:45:45: Fatal error encountered:
22:45:45: 
22:45:45: Traceback (most recent call last):
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\main.py", line 160, in main
22:45:45:     await client.run()
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\twitch.py", line 772, in run
22:45:45:     await self._run()
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\twitch.py", line 1017, in _run
22:45:45:     self.watch(new_watching)
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\twitch.py", line 1211, in watch
22:45:45:     self.print(status_text)
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\twitch.py", line 736, in print
22:45:45:     self.gui.print(message)
22:45:45:   File "C:\Users\Administrator\Desktop\TwitchDropsMiner_2024-5-fix\gui.py", line 2190, in print
22:45:45:     print(f"{datetime.now().strftime('%Y-%m-%d %X')}: {message}")
22:45:45: UnicodeEncodeError: 'gbk' codec can't encode character '\ud734' in position 31: illegal multibyte sequence
22:45:45: 
22:45:45: Exiting...
22:45:47: 
22:45:47: Application Terminated.
22:45:47: Close the window to exit the application.
```

OS: Windows Server 2012 R2 Datacenter

**Comment by dogodogowoof** [comment]
I also got 2 random terminations in a row, but now it's back to running well again.

**Comment by Windows200000** [comment]
It's a channel name containing [this](https://codepoints.net/U+D734).

Also, why is nobody using the issue templates?
