### ISSUE TITLE
Fatal error: GQL error "service error" "'gameEventDrops"

### ISSUE THREAD

**Issue by dogodogowoof** [Windows200000/TwitchDropsMiner-updated#138]
### Description

TDM Fatal error encountered when launching

### To Reproduce

1. Launch TDM

### Expected behavior

TDM launches and starts looking for drops

### Observed behavior

TDM encounters a Fatal error and stops functioning

### Screenshots

![image](https://github.com/Windows200000/TwitchDropsMiner-updated/assets/31750934/d7d1d5c3-64d6-4d74-9397-b7faf6217e98)

### Logs

16:35:15: Fatal error encountered:
16:35:15: 
16:35:15: Traceback (most recent call last):
16:35:15:   File "main.py", line 160, in main
16:35:15:   File "twitch.py", line 772, in run
16:35:15:   File "twitch.py", line 817, in _run
16:35:15:   File "twitch.py", line 1643, in fetch_inventory
16:35:15:   File "twitch.py", line 1575, in gql_request
16:35:15: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['currentUser', 'inventory', 'gameEventDrops']}]
16:35:15: 
16:35:15: Exiting...
16:35:16: 
16:35:16: Application Terminated.
16:35:16: Close the window to exit the application.

### OS

Windows 10

### Build

.exe

### Version/Commit

v15.7.0 (84f4882)

### Additional context

First encountered the issue while running the application normally, but since then, behavior follows as above.

**Comment by KevinNovak** [comment]
+1 also getting this issue on the latest release

**Comment by dogodogowoof** [comment]
seems to be randomly working for me now

**Comment by KevinNovak** [comment]
Also working again for me

**Comment by flamedance58** [comment]
Recently downloaded the newest version and got the error:

```
16:27:50: Fatal error encountered:
16:27:50: 
16:27:50: Traceback (most recent call last):
16:27:50:   File "main.py", line 160, in main
16:27:50:   File "twitch.py", line 772, in run
16:27:50:   File "twitch.py", line 817, in _run
16:27:50:   File "twitch.py", line 1670, in fetch_inventory
16:27:50:   File "asyncio\tasks.py", line 571, in _wait_for_one
16:27:50:   File "twitch.py", line 1608, in fetch_campaigns
16:27:50:   File "twitch.py", line 1575, in gql_request
16:27:50: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
16:27:50: 
16:27:50: Exiting...
16:27:50: 
16:27:50: Application Terminated.
16:27:50: Close the window to exit the application.
```
