### ISSUE TITLE
GQL error: [{'message': 'service error', 'path': ['currentUser', 'dropCampaigns']}]

### ISSUE THREAD

**Issue by 5wi5wi** [Windows200000/TwitchDropsMiner-updated#150]
### Description

TDM crashes while idling

### To Reproduce

you dont need to do anything

### Expected behavior

continues waiting for a drop to mine

### Observed behavior

the miner stopped and cant make it work again

### Logs

```
03:49:27: Fatal error encountered:
03:49:27: 
03:49:27: Traceback (most recent call last):
03:49:27:   File "main.py", line 160, in main
03:49:27:   File "twitch.py", line 772, in run
03:49:27:   File "twitch.py", line 817, in _run
03:49:27:   File "twitch.py", line 1652, in fetch_inventory
03:49:27:   File "twitch.py", line 1575, in gql_request
03:49:27: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['currentUser', 'dropCampaigns']}]
03:49:27: 
03:49:27: Exiting...
03:49:27: 
03:49:27: Application Terminated.
03:49:27: Close the window to exit the application.
```

### OS

Windows 11

### Build

.exe

### Version/Commit

v16.dev.8f3b6bd

**Comment by zelda0079** [comment]
Me too, but it is working again now.
