### ISSUE TITLE
Miner gets stuck on "Retrying connection"

### ISSUE THREAD

**Issue by WrayOfSunshine** [Windows200000/TwitchDropsMiner-updated#157]
### Description

TDM occasionally hits a brick wall where it cannot connect to Twitch and will retry for hours unsuccessfully. Exiting the application and starting it back up gets it back on track.

### To Reproduce

1. Run TDM for multiple hours; exact duration before error occurs varies.
2. Get wall of "Cannot connect, retrying" errors.

### Expected behavior

TDM should not continually fail to connect, or if it does have this issue, it should eventually fail out entirely instead of continuing to try to connect for multiple hours.

Arguably, if the process did a complete reset to initialization, this should resolve, since exiting the process manually and starting a fresh instance resolves.

### Observed behavior

TDM will continue to claim to be retrying the connection until it is manually exited, at which point initializing a fresh instance connects to Twitch successfully.

### Logs

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1022, in _wrap_create_connection
    async with ceil_timeout(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/src/websocket.py", line 124, in _backoff_connect
    async with session.ws_connect(ws_url, ssl=True, proxy=proxy) as websocket:
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 585, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host wss://pubsub-edge.twitch.tv/v1
2024-07-26 05:48:23.240:	   INFO:	Websocket[0] connection problem (sleep: 180s)
Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1022, in _wrap_create_connection
    async with ceil_timeout(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/src/websocket.py", line 124, in _backoff_connect
    async with session.ws_connect(ws_url, ssl=True, proxy=proxy) as websocket:
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 835, in _ws_connect
    resp = await self.request(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 585, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host wss://pubsub-edge.twitch.tv/v1
2024-07-26 05:53:40.262:	   INFO:	Websocket[0] connection problem (sleep: 180s)
Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/tmp/.mount_gearleV2chRz/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1022, in _wrap_create_connection
    async with ceil_timeout(
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/tmp/.mount_gearleV2chRz/usr/local/lib/python3.10/dist-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

```

### OS

Linux Mint

### Build

AppImage

### Version/Commit

v15.8.0

### Additional context

There are tons of exceptions like the one listed in the log, but my log file is 50MB so I don't want to copy/paste the whole thing and it is too large to upload to GitHub.

I will wipe it and try to catch a smaller one with the error.

**Comment by WrayOfSunshine** [comment]
Okay, managed to snag a log that's smaller than 25MB and has the issue.

[log.txt](https://github.com/user-attachments/files/16397578/log.txt)
