### ISSUE TITLE
Start up and got GQL error "PersistedQueryNotFound"

### ISSUE THREAD

**Issue by flamedance58** [Windows200000/TwitchDropsMiner-updated#160]
### Description

Start up the program and instantly get:

```
17:01:19: Fatal error encountered:
17:01:19: 
17:01:19: Traceback (most recent call last):
17:01:19:   File "main.py", line 160, in main
17:01:19:   File "twitch.py", line 772, in run
17:01:19:   File "twitch.py", line 817, in _run
17:01:19:   File "twitch.py", line 1670, in fetch_inventory
17:01:19:   File "asyncio\tasks.py", line 571, in _wait_for_one
17:01:19:   File "twitch.py", line 1608, in fetch_campaigns
17:01:19:   File "twitch.py", line 1575, in gql_request
17:01:19: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
17:01:19: 
17:01:19: Exiting...
17:01:19: 
17:01:19: Application Terminated.
17:01:19: Close the window to exit the application.
```

### To Reproduce

1, Start up miner

### Expected behavior

1. Either it should've started mining available streams of games I've set it up to do so.
OR
2. Just go to it's idle state and wait.

### Observed behavior

Error msg and being told to close down and restart the program.

### OS

Windows 10

### Build

.exe

### Version/Commit

v15.8

**Comment by flamedance58** [comment]
I re-downloaded the recent version and start it up and somehow it fixed it?
Not sure why this did it as I had already downloaded it a day ago..
I'll close it for now and hopefully the bug won't resurface.

My apologies for taking up anyone's time that sees this.
