### ISSUE TITLE
I need this on MacOS (Use WINE to open it on MacOS)

### ISSUE THREAD

**Issue by SlorRy** [Windows200000/TwitchDropsMiner-updated#171]
### Problem

How to run this program on macos :(

### Suggestion(s)

Add MacOS support, please

**Comment by TheLovinator1** [comment]
Have you tried to build from source?
https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

**Comment by SlorRy** [comment]
> Have you tried to build from source? I can help you it you get stuck https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

I tried but, .bat file's don't open on macos. May be If you could describe to me step by step what needs to be done, I would be very grateful

**Comment by TheLovinator1** [comment]
Oops, I thought there was files for Linux/macOS.

I am using Windows but try something like this:

1. [Install Python](https://www.python.org/downloads/macos/)
2. Download the project from GitHub
    2.1. You can download the project as a [zip file](https://github.com/Windows200000/TwitchDropsMiner-updated/archive/refs/heads/master.zip) from the GitHub page or clone it using Git
    2.2. If you download the project as a zip file, extract it to a folder
2. Open the terminal and navigate to the project folder
    2.1. For example: `cd /path/to/project`
    2.2. You can use tab completion to autocomplete the path by typing the first few letters of the folder name and pressing the `Tab` key
    2.3. You can use the `ls` command to list the files and folders in the current directory to verify that you are in the correct folder
3. Run the following command to install the dependencies:
    3.1. `python3 -m venv env`
    3.2. `source env/bin/activate`
    3.3. `pip install --upgrade pip`
    3.4. `pip install wheel`
    3.5. `pip install -r requirements.txt`
4. You only need to do this once, after that you can just run the project
    4.1. `python main.py`
    4.2. You may need to run `python main.py &` if you don't want the terminal to visible when the program is running

**Comment by SlorRy** [comment]
> 4\. ip install -r requirements.txt

Traceback (most recent call last):
  File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/main.py", line 198, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/main.py", line 154, in main
    client = Twitch(settings)
             ^^^^^^^^^^^^^^^^
  File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/twitch.py", line 630, in __init__
    self.gui = GUIManager(self)
               ^^^^^^^^^^^^^^^^
  File "/Users/slorry/Downloads/TwitchDropsMiner-updated-master/gui.py", line 1977, in __init__
    sublayout["children"] = sublayout["children"][0][1]["children"]
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'children'

**Comment by TheLovinator1** [comment]
Try to run `pip install tk` inside the terminal and run again

**Comment by SlorRy** [comment]
> Try to run `pip install tk` inside the terminal and run `python main.py`

same keyerror

**Comment by TheLovinator1** [comment]
Then I have no idea, sorry.

You can also try to open an issue in the [original repo](https://github.com/DevilXD/TwitchDropsMiner) while you wait for someone to help you in here

**Comment by Windows200000** [comment]
@SlorRy This has been suggested a while ago but never implemented. Likely because the original dev as well as me don't have macos and thus can't really develop for it.

Tho not supported and disliked by the original author, I think your usecase completely warrants it.

You can run it in docker, for now, but nothing is as permanent as a temporary solution. You'll find it on the second most starred fork (under mine).

**Comment by SlorRy** [comment]
> @SlorRy This has been suggested a while ago but never implemented. Likely because the original dev as well as me don't have macos and thus can't really develop for it.
> 
> Tho not supported and disliked by the original author, I think your usecase completely warrants it.
> 
> You can run it in docker, for now, but nothing is as permanent as a temporary solution. You'll find it on the second most starred fork (under mine).

so how to run it in docker? i never us it :(

**Comment by SlorRy** [comment]
So, i finally opened it with Wine. Ty @Windows200000 & @TheLovinator1 for trying to help me :)

**Comment by Windows200000** [comment]
I want to keep this open as a unique feature request to avoid duplicates.
