### ISSUE TITLE
% Desync

### ISSUE THREAD

**Issue by T4bletopG4mes** [Windows200000/TwitchDropsMiner-updated#177]
### Description

There seems to be a sync problem where TDM thinks it has mined a larger % than what the drops inventory shows. 

### To Reproduce

Mine any drop I guess.

### Expected behavior

Show a similar percentage to twitch drops inventory page (browser).

### Observed behavior

I have noticed the percentage deviating for up to 4% from what the inventory page shows (having seen what TDM shows, reloading the twitch inventory page on my browser and seeing what it shows there). It eventually catches up, however this causes problems when a stage is close to 100% since TDM says there are 0 seconds left but of course it cant claim the drop since on twitch's end there is 1% or more left. This is quite annoying when it happens to very time limited drops like the Warframe ones.

### OS

Windows 10 (64-bit)

### Build

.exe

### Version/Commit

Both latest dev build and stable release

### Additional context

Could be related with the "Cannot connect to Twitch, retrying" error

**Comment by Windows200000** [comment]
Are you using [v15.9.0](https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.9.0)?

**Comment by T4bletopG4mes** [comment]
Yep and it still exists unfortunately..
![image](https://github.com/user-attachments/assets/94de754b-21bc-45e0-9473-66b1de73f6a9)
![image](https://github.com/user-attachments/assets/f8d8f43b-c140-4d5e-975c-0a5cb09970bc)

**Comment by T4bletopG4mes** [comment]
Maybe having other non-drop livestreams open affects it?

**Comment by T4bletopG4mes** [comment]
New Error code

22:32:17: ERROR: Exception in task
22:32:17: Traceback (most recent call last):
22:32:17:   File "aiohttp\client_proto.py", line 94, in connection_lost
22:32:17:   File "aiohttp\\_http_parser.pyx", line 513, in aiohttp._http_parser.HttpParser.feed_eof
22:32:17: aiohttp.http_exceptions.TransferEncodingError: 400, message:
22:32:17:   Not enough data for satisfy transfer length header.
22:32:17: 
22:32:17: The above exception was the direct cause of the following exception:
22:32:17: 
22:32:17: Traceback (most recent call last):
22:32:17:   File "utils.py", line 139, in wrapper
22:32:17:   File "twitch.py", line 1049, in _watch_loop
22:32:17:   File "channel.py", line 419, in send_watch
22:32:17:   File "contextlib.py", line 199, in __aenter__
22:32:17:   File "twitch.py", line 1513, in request
22:32:17:   File "aiohttp\client_reqrep.py", line 1134, in read
22:32:17:   File "aiohttp\streams.py", line 383, in read
22:32:17:   File "aiohttp\streams.py", line 405, in readany
22:32:17:   File "aiohttp\streams.py", line 312, in _wait
22:32:17: aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>. ConnectionResetError(22, 'The specified network name is no longer available', None, 64, None)

**Comment by Windows200000** [comment]
That looks like you have problems with your ISP. I'll leave it open if more people report this.

**Comment by VatriXxX** [comment]
I have a % desync too, but i didn't have the error code of T4bletopG4mes.
Mine is jumping, for example from 77/120 to 68/120 or like in that screenshot.
![grafik](https://github.com/user-attachments/assets/8ce32f31-f458-4006-8907-d8222620f2a2)

This problem is since today. I haven't had this problem in the last few days.

**Comment by T4bletopG4mes** [comment]
The error could be unrelated but desync seems to happen, although its probably more Twitch's than TDM's fault.
